### ISSUE TITLE
Retry connection failures

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spice.js#118]
When our service terminates the HTTP2 connection that the Node SDK starts, the SDK returns this error back to the client:

```
    Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
    at h (webpack:///spice/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (webpack:///spice/node_modules/@grpc/grpc-js/build/src/client.js:192:56)
    at status (webpack:///spice/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at status (webpack:///spice/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at <anonymous> (webpack:///spice/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at o.makeUnaryRequest (webpack:///spice/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at o.<anonymous> (webpack:///spice/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at N (webpack:///spice/node_modules/@spiceai/spice/dist/client.js:92:20)
    at new Promise (<anonymous>)
    at S.getResultStream (webpack:///spice/node_modules/@spiceai/spice/dist/client.js:90:34)
    at S.query (webpack:///spice/node_modules/@spiceai/spice/dist/client.js:139:35)
    at <anonymous> (webpack:///spice/integrations/spice-integration.ts:773:36)
    at le (/var/task/handlers/handler.js:404:662578)
    at Object.next (/var/task/handlers/handler.js:404:661808)
    at /var/task/handlers/handler.js:404:661496 {
  code: 13,
  details: 'Received RST_STREAM with code 2 (Internal server error)',
  metadata: c { internalRepr: Map(0) {}, options: {} }
}
```

This is a normal error that occurs when Nginx kills the connection for being open too long, or serving too many requests. We should improve the SDK to automatically retry these failures and re-open a connection and retry the request.

**Comment by sgrebnov** [comment]
[SDK version 1.0.1 ](https://github.com/spiceai/spice.js/releases/tag/v1.0.1)with retry logic implementation has been just released. The customer reported this problem has been notified to confirm the issue is actually gone. Will re-open if it is not.
